"use strict";

// Faces for the address book.
//
// A contact list of grey initials is a database; a contact list of faces is something the owner can
// read at a glance. The picker proved the point in the worst way — two rows both reading "Tg" were
// unanswerable precisely because there was nothing to look at.
//
// The obvious implementation is to store the CDN URL and let the browser load it. That fails
// quietly and permanently: Instagram's image URLs are signed and expire, so every face in the book
// turns into a broken image some days later, which is the failure mode the owner would notice last
// and trust least. So the bytes are fetched once and kept.
//
// Two rules this module exists to enforce:
//   1. nothing is written that was not actually decoded as an image — a 404 HTML page saved as
//      "avatar.jpg" renders as a broken tile, which looks identical to a bug in the UI;
//   2. the path written to the store is derived from the contact id, never from anything the remote
//      server said, so a hostile filename cannot escape the cache directory.

const fs = require("fs");
const path = require("path");

const MAX_BYTES = 4 * 1024 * 1024;
const FETCH_TIMEOUT_MS = 12000;

// Magic numbers, because the content-type header is whatever the server felt like sending.
const SIGNATURES = [
  { ext: "jpg",  bytes: [0xff, 0xd8, 0xff] },
  { ext: "png",  bytes: [0x89, 0x50, 0x4e, 0x47] },
  { ext: "gif",  bytes: [0x47, 0x49, 0x46, 0x38] },
  { ext: "webp", bytes: [0x52, 0x49, 0x46, 0x46], at: 0, also: { at: 8, bytes: [0x57, 0x45, 0x42, 0x50] } },
];

function startsWith(buffer, bytes, at = 0) {
  if (buffer.length < at + bytes.length) return false;
  return bytes.every((byte, index) => buffer[at + index] === byte);
}

// The real format, or "" if these bytes are not an image at all.
function imageKind(buffer) {
  for (const signature of SIGNATURES) {
    if (!startsWith(buffer, signature.bytes, signature.at || 0)) continue;
    if (signature.also && !startsWith(buffer, signature.also.bytes, signature.also.at)) continue;
    return signature.ext;
  }
  return "";
}

const CONTENT_TYPES = { jpg: "image/jpeg", png: "image/png", gif: "image/gif", webp: "image/webp" };

function contentTypeFor(filePath) {
  return CONTENT_TYPES[String(filePath).split(".").pop().toLowerCase()] || "application/octet-stream";
}

function createAvatarCache({ runtimeDir } = {}) {
  if (!runtimeDir) throw new Error("runtimeDir is required");
  const dir = path.join(runtimeDir, "contact-avatars");

  // Only ever `<cache>/<contactId>.<ext>`. The id is generated by the store (a UUID), and the
  // extension comes from the decoded bytes — neither is remote-controlled.
  function pathFor(contactId, ext) {
    const safeId = String(contactId || "").replace(/[^A-Za-z0-9_-]/g, "");
    if (!safeId) throw new Error("A contact id is required to cache an avatar");
    return path.join(dir, `${safeId}.${ext}`);
  }

  function existingFor(contactId) {
    const safeId = String(contactId || "").replace(/[^A-Za-z0-9_-]/g, "");
    if (!safeId) return "";
    for (const ext of Object.keys(CONTENT_TYPES)) {
      const candidate = path.join(dir, `${safeId}.${ext}`);
      if (fs.existsSync(candidate)) return candidate;
    }
    return "";
  }

  function clear(contactId) {
    const existing = existingFor(contactId);
    if (!existing) return false;
    fs.unlinkSync(existing);
    return true;
  }

  // Downloads one image and keeps it only if it really is one.
  async function store(contactId, imageUrl, { fetchImpl = fetch } = {}) {
    const url = String(imageUrl || "").trim();
    if (!/^https:\/\//i.test(url)) throw new Error("An avatar must come from an https URL");

    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), FETCH_TIMEOUT_MS);
    let response;
    try {
      response = await fetchImpl(url, { signal: controller.signal, redirect: "follow" });
    } finally {
      clearTimeout(timer);
    }
    if (!response?.ok) throw new Error(`The image could not be fetched (HTTP ${response?.status ?? "?"})`);

    const buffer = Buffer.from(await response.arrayBuffer());
    if (!buffer.length) throw new Error("The image was empty");
    if (buffer.length > MAX_BYTES) throw new Error(`The image is too large (${Math.round(buffer.length / 1024)} KB)`);

    const kind = imageKind(buffer);
    // The check that matters. Instagram answers an expired URL with an HTML error page and a 200,
    // and without this the address book fills up with files that are not pictures.
    if (!kind) throw new Error("That URL did not return an image");

    fs.mkdirSync(dir, { recursive: true });
    // A contact has one face; a format change must not leave the old file behind to be found first.
    clear(contactId);
    const destination = pathFor(contactId, kind);
    fs.writeFileSync(destination, buffer, { mode: 0o600 });
    return { path: destination, bytes: buffer.length, kind };
  }

  return { clear, contentTypeFor, dir, existingFor, imageKind, pathFor, store };
}

module.exports = { contentTypeFor, createAvatarCache, imageKind };
