"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const { afterEach, test } = require("node:test");
const { createApexForgeIntegration, createExperienceLearning, createHelixIntegration, createRetrievalPlanner, openCoreStore } = require("../../server/memory-vnext");

const roots = []; const stores = [];
function protector() { const mask = 0x64; return Object.freeze({ id: "waves24-26-test-protector", protect(bytes) { return Buffer.concat([Buffer.from("W2426"), Buffer.from(bytes).map((value) => value ^ mask)]); }, unprotect(bytes) { const value = Buffer.from(bytes); if (value.subarray(0, 5).toString() !== "W2426") throw new Error("bad wrapper"); return value.subarray(5).map((item) => item ^ mask); } }); }
async function core(options = {}) { const root = fs.mkdtempSync(path.join(os.tmpdir(), "jarvis-memory-w2426-")); roots.push(root); const store = await openCoreStore({ runtimeDir: root, allowUnsafeTestPath: true, keyProtector: protector(), targetVersion: options.targetVersion || 24, clock: options.clock, faultInjector: options.faultInjector }); stores.push(store); return store; }
function environment(overrides = {}) { return { os: "windows", arch: "x64", runtime: "node20", app: "jarvis", ...overrides }; }
function verification(learning, { id, success, group, env = environment(), taskId } = {}) { return learning.verifyOutcome({ id, scopeId: "owner:local", taskId: taskId || `task:${id}`, outcomeKind: "task", success, evaluatorKind: "deterministic", criteria: [{ id: "completed", passed: success, evidenceRefs: [{ type: "receipt", id: `receipt:${id}`, version: "1" }] }], evidenceRefs: [{ type: "receipt", id: `receipt:${id}`, version: "1" }], environment: env, independentGroup: group || `independent:${id}`, verifiedBy: "local-owner" }); }
function experienceCase(learning, { id, type, success, group, env = environment() }) { const verified = verification(learning, { id: `verify:${id}`, success, group, env, taskId: `task:${id}` }); return learning.createCase({ id, verificationId: verified.id, caseType: type, taskSignature: "desktop.file.move", taskClass: "desktop.file.move", trajectorySummary: { outcome: type, lastStep: "verified" }, inputRefs: [{ type: "file", id: `input:${id}`, version: "1" }], outputRefs: [{ type: "receipt", id: `output:${id}`, version: "1" }], toolRefs: [{ type: "tool", id: "filesystem.move", version: "1" }], permissions: ["filesystem.move"] }); }
function candidateFixture(learning, { risk = "low", sideEffecting = true } = {}) { const success = experienceCase(learning, { id: "case:success", type: "success", success: true, group: "machine:a" }); const failure = experienceCase(learning, { id: "case:failure", type: "failure", success: false, group: "machine:b" }); const counter = experienceCase(learning, { id: "case:counter", type: "counterexample", success: true, group: "machine:c" }); const candidate = learning.createLessonCandidate({ clusterId: success.clusterId, name: "Move a verified file", blueprint: { steps: [{ id: "resolve", action: "resolve-source" }, { id: "move", action: "filesystem.move" }], stopConditions: ["source-missing"] }, environmentSelector: { os: "windows", runtime: "node20" }, inputs: ["sourcePath", "destinationPath"], outputs: ["moveReceipt"], tools: ["filesystem.move"], permissions: ["filesystem.move"], successCaseIds: [success.id], failureCaseIds: [failure.id], counterexampleCaseIds: [counter.id], risk, sideEffecting, minReliability: 0.8, createdBy: "local-owner" }); return { success, failure, counter, candidate }; }
function passingCases(fixture) { return [fixture.success, fixture.failure, fixture.counter].map((item) => ({ caseId: item.id, passed: true, environmentMatch: true, permissionViolation: false, score: 1 })); }
function ref(kind, id, version = "1", pointer = null) { return { kind, id, version, ...(pointer ? { pointer } : {}) }; }
afterEach(() => { while (stores.length) stores.pop().close(); while (roots.length) fs.rmSync(roots.pop(), { recursive: true, force: true }); });

test("Waves 24-26 upgrade Wave 23 through a verified backup with every application table STRICT", async () => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "jarvis-memory-w2426-upgrade-")); roots.push(root); const old = await openCoreStore({ runtimeDir: root, allowUnsafeTestPath: true, keyProtector: protector(), targetVersion: 21 }); old.putEncryptedObject({ id: "before-wave24", objectType: "fixture", scopeId: "owner:local", sensitivity: "private", payload: { survives: true } }); old.close(); const current = await openCoreStore({ runtimeDir: root, allowUnsafeTestPath: true, keyProtector: protector(), targetVersion: 24 }); stores.push(current); assert.deepEqual(current.getEncryptedObject("before-wave24").payload, { survives: true }); const audit = current.attachRepository(({ db }) => { const tables = db.prepare("PRAGMA table_list").all().filter((row) => row.type === "table" && !String(row.name).startsWith("sqlite_")); return { version: Number(db.pragma("user_version", { simple: true })), backups: db.prepare("SELECT COUNT(*) AS count FROM backup_history").get().count, nonStrict: tables.filter((row) => row.strict !== 1).map((row) => row.name), migrations: db.prepare("SELECT version FROM schema_migrations ORDER BY version").all().map((row) => row.version) }; }); assert.equal(audit.version, 24); assert.equal(audit.backups, 1); assert.deepEqual(audit.nonStrict, []); assert.deepEqual(audit.migrations, Array.from({ length: 24 }, (_, index) => index + 1));
});

test("Wave 26 migration crash rolls back to Wave 25 and recovers without partial APEX tables", async () => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "jarvis-memory-w26-fault-")); roots.push(root); const old = await openCoreStore({ runtimeDir: root, allowUnsafeTestPath: true, keyProtector: protector(), targetVersion: 23 }); old.close(); await assert.rejects(openCoreStore({ runtimeDir: root, allowUnsafeTestPath: true, keyProtector: protector(), targetVersion: 24, faultInjector(point) { if (point === "migration.24.before_commit") throw new Error("wave26 migration crash"); } }), /wave26 migration crash/); const Database = require("better-sqlite3"); const db = new Database(path.join(root, "memory-vnext.sqlite")); assert.equal(Number(db.pragma("user_version", { simple: true })), 23); assert.equal(db.prepare("SELECT COUNT(*) AS count FROM sqlite_schema WHERE type='table' AND name='forge_run_manifests'").get().count, 0); db.close(); const recovered = await openCoreStore({ runtimeDir: root, allowUnsafeTestPath: true, keyProtector: protector(), targetVersion: 24 }); stores.push(recovered); assert.equal(recovered.health().schemaVersion, 24);
});

test("Wave 24 creates cases only from evidence-backed criteria and never stores raw reasoning", async () => {
  const store = await core(); const learning = createExperienceLearning({ store }); assert.throws(() => learning.verifyOutcome({ scopeId: "owner:local", taskId: "task:no-evidence", success: true, criteria: [{ id: "done", passed: true }], evidenceRefs: [], environment: environment(), independentGroup: "g", verifiedBy: "local-owner" }), (error) => error.code === "OUTCOME_EVIDENCE_REQUIRED"); assert.throws(() => learning.verifyOutcome({ scopeId: "owner:local", taskId: "task:mismatch", success: true, criteria: [{ id: "done", passed: false }], evidenceRefs: [{ type: "receipt", id: "r:1", version: "1" }], environment: environment(), independentGroup: "g", verifiedBy: "local-owner" }), (error) => error.code === "OUTCOME_CRITERIA_MISMATCH"); const verified = verification(learning, { id: "verify:safe", success: true, group: "machine:a" }); assert.throws(() => learning.createCase({ verificationId: verified.id, caseType: "success", taskSignature: "desktop.file.move", trajectorySummary: { reasoningTrace: "hidden thought" } }), (error) => error.code === "EXPERIENCE_PAYLOAD_FORBIDDEN"); const first = learning.createCase({ verificationId: verified.id, caseType: "success", taskSignature: "desktop.file.move", taskClass: "desktop.file.move", trajectorySummary: { outcome: "moved", steps: 2 } }); assert.ok(first.clusterId); const raw = fs.readFileSync(store.paths.dbPath); assert.equal(raw.includes(Buffer.from("hidden thought")), false); assert.equal(raw.includes(Buffer.from("moved")), false);
});

test("Wave 24 requires success, failure, counterexample, environment and owner gates before promotion", async () => {
  const store = await core(); const learning = createExperienceLearning({ store }); const fixture = candidateFixture(learning); assert.throws(() => learning.runLessonTests({ candidateId: fixture.candidate.id, results: passingCases(fixture).slice(0, 2) }), (error) => error.code === "LESSON_TEST_COVERAGE_INCOMPLETE"); const failed = learning.runLessonTests({ candidateId: fixture.candidate.id, results: passingCases(fixture).map((item, index) => index === 2 ? { ...item, environmentMatch: false } : item) }); assert.equal(failed.passed, false); const retry = learning.runLessonTests({ candidateId: fixture.candidate.id, results: passingCases(fixture) }); assert.equal(retry.status, "ready_review"); assert.throws(() => learning.approveCandidate({ candidateId: fixture.candidate.id, actorId: "local-system", authorityZone: "owner" }), (error) => error.code === "OWNER_AUTHORITY_REQUIRED"); learning.approveCandidate({ candidateId: fixture.candidate.id, actorId: "local-owner", authorityZone: "owner" }); const promoted = learning.promoteCandidate({ candidateId: fixture.candidate.id, actorId: "local-owner", authorityZone: "owner" }); const denied = learning.selectProcedure({ scopeId: "owner:local", taskSignature: "desktop.file.move", environment: environment({ runtime: "node22" }), allowedTools: ["filesystem.move"], allowedPermissions: ["filesystem.move"] }); assert.equal(denied.reasonCode, "ENVIRONMENT_MISMATCH"); const selected = learning.selectProcedure({ scopeId: "owner:local", taskSignature: "desktop.file.move", environment: environment(), allowedTools: ["filesystem.move"], allowedPermissions: ["filesystem.move"] }); assert.equal(selected.available, true); assert.equal(selected.versionId, promoted.versionId); const adapter = learning.createAdapter({ procedureVersionId: promoted.versionId, adapterType: "langgraph" }); assert.equal(adapter.manifest.approvalRequiredAtExecution, true);
});

test("Wave 24 ignores environment-mismatched outcomes and suspends a procedure after verified regression", async () => {
  const store = await core(); const learning = createExperienceLearning({ store }); const fixture = candidateFixture(learning); learning.runLessonTests({ candidateId: fixture.candidate.id, results: passingCases(fixture) }); learning.approveCandidate({ candidateId: fixture.candidate.id, actorId: "local-owner", authorityZone: "owner" }); const promoted = learning.promoteCandidate({ candidateId: fixture.candidate.id, actorId: "local-owner", authorityZone: "owner" }); const mismatch = verification(learning, { id: "verify:linux-failure", success: false, env: environment({ os: "linux" }) }); assert.equal(learning.recordProcedureOutcome({ procedureVersionId: promoted.versionId, verificationId: mismatch.id }).action, "ignore_environment"); assert.equal(learning.readProcedure(promoted.procedureId).status, "active"); const failure1 = verification(learning, { id: "verify:regression1", success: false }); const failure2 = verification(learning, { id: "verify:regression2", success: false }); assert.equal(learning.recordProcedureOutcome({ procedureVersionId: promoted.versionId, verificationId: failure1.id }).suspended, false); assert.equal(learning.recordProcedureOutcome({ procedureVersionId: promoted.versionId, verificationId: failure2.id }).suspended, true); assert.equal(learning.readProcedure(promoted.procedureId).suspensionReason, "VERIFIED_RELIABILITY_REGRESSION"); assert.equal(learning.selectProcedure({ scopeId: "owner:local", taskSignature: "desktop.file.move", environment: environment(), allowedTools: ["filesystem.move"], allowedPermissions: ["filesystem.move"] }).available, false);
});

test("Wave 24 retrieval utility requires a scope-matched verified outcome receipt", async () => {
  const store = await core(); const planner = createRetrievalPlanner({ store }); const plan = planner.plan({ scopeId: "owner:local", query: "find the relevant procedure", uncertainty: 0.5 }); assert.throws(() => planner.recordOutcome({ planId: plan.id, outcomeType: "helpful", verified: true }), (error) => error.code === "RETRIEVAL_OUTCOME_VERIFICATION_REQUIRED"); const learning = createExperienceLearning({ store }); const verified = verification(learning, { id: "verify:retrieval", success: true }); const result = planner.recordOutcome({ planId: plan.id, outcomeType: "helpful", verified: true, verificationId: verified.id, supportedClaims: 1 }); assert.equal(result.utilityDelta, 0.25); const row = store.attachRepository(({ db }) => db.prepare("SELECT verification_id,verified FROM retrieval_outcomes WHERE id=?").get(result.id)); assert.deepEqual(row, { verification_id: verified.id, verified: 1 });
});

test("Wave 25 publishes HELIX project, folder and segment packages without internal model calls or source bodies", async () => {
  const store = await core(); const helix = createHelixIntegration({ store }); const manifest = helix.publishResearchSnapshot({ scopeId: "owner:local", allowedScopeIds: ["owner:local"], projectId: "helix:project:1", status: "researching", objective: "Evaluate market entry", summary: "Evidence collection is complete; one contradiction remains open.", openLoops: [{ id: "loop:contradiction", state: "open" }], warnings: ["One source is stale"], cost: { usd: 0.02, inputTokens: 1200 }, sourceSequence: 1, projects: [ref("project", "helix:project:1", "3", { table: "helix_projects", key: "helix:project:1" })], folders: [ref("folder", "folder:markets", "2")], segments: [ref("segment", "segment:strategy", "1")], questions: [ref("question", "question:entry", "1")], plans: [ref("plan", "plan:research", "2")], runs: [ref("run", "run:deep", "4")], sources: [ref("source", "source:report", "2", { table: "helix_sources", key: "source:report" })], evidence: [ref("evidence", "evidence:growth", "3")], claims: [ref("claim", "claim:growth", "1")], decisions: [ref("decision", "decision:enter", "1")], artifacts: [ref("artifact", "artifact:brief", "2")], internalModelCalls: [{ id: "helix-call:extract:1" }, { id: "helix-call:synthesis:2" }], packages: [{ type: "folder", ref: "folder:markets", version: "2", payload: { summary: "Market evidence", status: "complete", openQuestions: ["pricing"] }, refs: [ref("source", "source:report", "2"), ref("evidence", "evidence:growth", "3")] }, { type: "segment", ref: "segment:strategy", version: "1", payload: { summary: "Strategy subset", status: "active" }, refs: [ref("claim", "claim:growth", "1"), ref("decision", "decision:enter", "1")] }], lineage: [{ from: ref("source", "source:report", "2"), to: ref("evidence", "evidence:growth", "3"), relation: "derived_from" }, { from: ref("evidence", "evidence:growth", "3"), to: ref("claim", "claim:growth", "1"), relation: "supports" }, { from: ref("run", "run:deep", "4"), to: ref("artifact", "artifact:brief", "2"), relation: "produces" }] }); assert.equal(manifest.excludedRefCount, 2); const current = helix.currentProject({ projectId: "helix:project:1", allowedScopeIds: ["owner:local"] }); assert.equal(current.refs.some((item) => item.id === "helix-call:extract:1"), false); assert.equal(current.exclusions[0].kind, "internal_model"); assert.equal(current.packages.length, 2); assert.equal(current.refs.find((item) => item.id === "source:report").pointer.table, "helix_sources"); assert.equal(fs.readFileSync(store.paths.dbPath).includes(Buffer.from("Evidence collection is complete")), false);
});

test("Wave 25 enforces monotonic manifests, exact replay, scope isolation and pointer-only references", async () => {
  const store = await core(); const helix = createHelixIntegration({ store }); const base = { scopeId: "owner:local", allowedScopeIds: ["owner:local"], projectId: "helix:project:2", status: "active", objective: "Research", summary: "Started", sourceSequence: 1, projects: [ref("project", "helix:project:2", "1")] }; const first = helix.publishResearchSnapshot(base); assert.equal(helix.publishResearchSnapshot(base).replayed, true); assert.throws(() => helix.publishResearchSnapshot({ ...base, summary: "different" }), (error) => error.code === "ROOM_MANIFEST_SEQUENCE_CONFLICT"); const second = helix.publishResearchSnapshot({ ...base, sourceSequence: 2, summary: "Advanced", questions: [ref("question", "question:2", "1")] }); assert.equal(second.supersedesManifestId, first.id); assert.throws(() => helix.currentProject({ projectId: base.projectId, allowedScopeIds: ["project:other"] }), (error) => error.code === "ROOM_SCOPE_DENIED"); assert.throws(() => helix.publishResearchSnapshot({ ...base, projectId: "helix:raw", sourceSequence: 1, sources: [{ id: "source:raw", version: "1", text: "entire source body" }] }), (error) => error.code === "ROOM_RAW_BODY_REJECTED");
});

test("Wave 25 exposes reproducible HELIX evidence-to-claim-to-decision and run-to-artifact lineage", async () => {
  const store = await core(); const helix = createHelixIntegration({ store }); const manifest = helix.publishResearchSnapshot({ scopeId: "owner:local", projectId: "helix:project:lineage", status: "complete", objective: "Choose", summary: "Decision locked", sourceSequence: 1, evidence: [ref("evidence", "e:1")], claims: [ref("claim", "c:1")], decisions: [ref("decision", "d:1")], runs: [ref("run", "r:1")], artifacts: [ref("artifact", "a:1")], lineage: [{ from: ref("evidence", "e:1"), to: ref("claim", "c:1"), relation: "supports" }, { from: ref("claim", "c:1"), to: ref("decision", "d:1"), relation: "supports" }, { from: ref("run", "r:1"), to: ref("artifact", "a:1"), relation: "produces" }] }); const decision = helix.explainLineage({ manifestId: manifest.id, refKind: "decision", refId: "d:1", allowedScopeIds: ["owner:local"] }); assert.deepEqual(decision.map((edge) => edge.fromId), ["c:1"]); assert.equal(helix.explainLineage({ manifestId: manifest.id, refKind: "artifact", refId: "a:1", allowedScopeIds: ["owner:local"] })[0].fromId, "r:1");
});

test("Wave 26 keeps APEX raw data domain-owned and routes stale/live data through freshness contracts", async () => {
  let nowMs = Date.parse("2026-07-26T10:00:00.000Z"); const store = await core({ clock: () => new Date(nowMs) }); const apex = createApexForgeIntegration({ store }); const manifest = apex.publishApexSnapshot({ scopeId: "owner:local", projectId: "apex:markets", status: "active", objective: "Monitor", summary: "Live market monitoring", sourceSequence: 1, datasets: [ref("dataset", "dataset:bars", "2026-07-26", { table: "apex_bars", ticker: "SPY" })], signals: [ref("signal", "signal:risk", "4")], reports: [ref("report", "report:morning", "1")], rawDataRefs: [{ id: "apex_bars:SPY:1m" }], telemetryRefs: [{ id: "ingest-latency:1" }] }); assert.equal(manifest.excludedRefCount, 2); const live = apex.registerFreshness({ scopeId: "owner:local", refType: "quote", refId: "SPY", refVersion: "2026-07-26T10:00", asOf: new Date(nowMs).toISOString(), maxAgeSeconds: 60, route: "live_pointer", sourceHealth: "healthy", pointer: { adapter: "apex.quote", ticker: "SPY" } }); assert.equal(live.state, "fresh"); assert.equal(apex.resolveFreshness({ scopeId: "owner:local", allowedScopeIds: ["owner:local"], refType: "quote", refId: "SPY" }).requiresLiveFetch, true); nowMs += 61000; const stale = apex.resolveFreshness({ scopeId: "owner:local", allowedScopeIds: ["owner:local"], refType: "quote", refId: "SPY" }); assert.equal(stale.freshness, "stale"); assert.equal(stale.mayUseSnapshot, false); assert.equal(apex.currentApexProject({ projectId: "apex:markets", allowedScopeIds: ["owner:local"] }).refs.length, 3);
});

test("Wave 26 publishes Forge branch/block/mutation lineage and validated outcomes without copying telemetry", async () => {
  const store = await core(); const apex = createApexForgeIntegration({ store }); const run = apex.publishForgeRun({ scopeId: "owner:local", projectId: "apex:forge", strategy: { id: "strategy:momentum", version: "7", pointer: { table: "apex_strategies", key: "strategy:momentum" } }, graphVersion: "graph:9", status: "selected", objective: "Improve risk-adjusted return", summary: "Mutation m2 selected after walk-forward validation", sourceSequence: 1, branches: [{ id: "branch:root", version: "1", status: "tested" }, { id: "branch:m2", version: "2", parentId: "branch:root", status: "selected" }], blocks: [{ id: "block:rsi", version: "3", type: "signal" }], mutations: [{ id: "mutation:m2", version: "2", status: "accepted", branchId: "branch:m2", testId: "test:wf" }], datasets: [ref("dataset", "dataset:daily", "2026-07")], signals: [ref("signal", "signal:rsi", "3")], tests: [ref("test", "test:wf", "2")], reports: [ref("report", "report:deep", "1")], metrics: { sharpe: 1.4, maxDrawdownPct: 8.2, outOfSample: true }, selection: { mutationId: "mutation:m2", rationaleCode: "OOS_PASS" }, lineage: [{ from: ref("strategy", "strategy:momentum", "7"), to: ref("dataset", "dataset:daily", "2026-07"), relation: "uses" }, { from: ref("mutation", "mutation:m2", "2"), to: ref("test", "test:wf", "2"), relation: "tests" }, { from: ref("test", "test:wf", "2"), to: ref("report", "report:deep", "1"), relation: "produces" }], telemetryRefs: [{ id: "backtest-loop-timing" }] }); const restored = apex.readForgeRun({ id: run.id, allowedScopeIds: ["owner:local"] }); assert.equal(restored.lineage.length, 3); assert.equal(restored.manifest.mutations[0].status, "accepted"); const validation = apex.recordValidation({ scopeId: "owner:local", targetType: "strategy", targetId: "strategy:momentum", targetVersion: "7", outcome: "passed", metrics: { sharpe: 1.4, outOfSample: true }, evidenceRefs: [{ type: "test", id: "test:wf", version: "2" }] }); assert.equal(validation.outcome, "passed"); assert.throws(() => apex.publishForgeRun({ scopeId: "owner:local", projectId: "apex:raw", strategy: { id: "strategy:raw", version: "1" }, graphVersion: "1", sourceSequence: 1, metrics: { equityCurve: [1, 2, 3] } }), (error) => error.code === "APEX_RAW_DATA_REJECTED");
});

test("Waves 24-26 controlled faults leave no partial verification, room, Forge, or freshness payloads", async () => {
  let crashPoint = null; const store = await core({ faultInjector(point) { if (point === crashPoint) throw new Error(`controlled ${point}`); } }); const learning = createExperienceLearning({ store }); crashPoint = "experience.verify.before_commit"; assert.throws(() => verification(learning, { id: "verify:fault", success: true }), /controlled/); crashPoint = null; const helix = createHelixIntegration({ store }); crashPoint = "room.publish.before_commit"; assert.throws(() => helix.publishResearchSnapshot({ scopeId: "owner:local", projectId: "helix:fault", status: "active", objective: "x", summary: "rollback room", sourceSequence: 1, projects: [ref("project", "helix:fault")] }), /controlled/); crashPoint = null; const apex = createApexForgeIntegration({ store }); crashPoint = "apex.forge_publish.before_commit"; assert.throws(() => apex.publishForgeRun({ scopeId: "owner:local", projectId: "forge:fault", strategy: { id: "strategy:fault", version: "1" }, graphVersion: "1", sourceSequence: 1, status: "tested", metrics: {} }), /controlled/); crashPoint = "apex.freshness.before_commit"; assert.throws(() => apex.registerFreshness({ scopeId: "owner:local", refType: "quote", refId: "FAULT", refVersion: "1", asOf: new Date().toISOString(), maxAgeSeconds: 60, pointer: { adapter: "apex.quote" } }), /controlled/); crashPoint = null; const state = store.attachRepository(({ db }) => ({ verifications: db.prepare("SELECT COUNT(*) AS count FROM outcome_verifications").get().count, verificationPayloads: db.prepare("SELECT COUNT(*) AS count FROM encrypted_objects WHERE object_type LIKE 'outcome-verification-%'").get().count, rooms: db.prepare("SELECT COUNT(*) AS count FROM room_manifests").get().count, roomPayloads: db.prepare("SELECT COUNT(*) AS count FROM encrypted_objects WHERE object_type LIKE 'room-%'").get().count, forge: db.prepare("SELECT COUNT(*) AS count FROM forge_run_manifests").get().count, freshness: db.prepare("SELECT COUNT(*) AS count FROM apex_freshness_contracts").get().count, apexPayloads: db.prepare("SELECT COUNT(*) AS count FROM encrypted_objects WHERE object_type LIKE 'apex-%' OR object_type LIKE 'forge-%'").get().count })); assert.deepEqual(state, { verifications: 0, verificationPayloads: 0, rooms: 0, roomPayloads: 0, forge: 0, freshness: 0, apexPayloads: 0 });
});
