"use strict";

const assert = require("node:assert/strict");
const crypto = require("node:crypto");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const { afterEach, test } = require("node:test");
const { createEclipseMemoryIntegration, createExperienceLearning, createMemoryOperations, createMeshMemorySync, openCoreStore } = require("../../server/memory-vnext");

const roots = []; const stores = [];
function protector() { const mask = 0x29; return Object.freeze({ id: "waves27-29-test-protector", protect(bytes) { return Buffer.concat([Buffer.from("W2729"), Buffer.from(bytes).map((value) => value ^ mask)]); }, unprotect(bytes) { const value = Buffer.from(bytes); if (value.subarray(0, 5).toString() !== "W2729") throw new Error("bad wrapper"); return value.subarray(5).map((item) => item ^ mask); } }); }
async function core(options = {}) { const root = fs.mkdtempSync(path.join(os.tmpdir(), "jarvis-memory-w2729-")); roots.push(root); const store = await openCoreStore({ runtimeDir: root, allowUnsafeTestPath: true, keyProtector: protector(), targetVersion: options.targetVersion || 27, clock: options.clock, faultInjector: options.faultInjector }); stores.push(store); return store; }
function ref(id, version = "1", recall = {}) { return { id, version, recall, pointer: { table: "eclipse", key: id } }; }
function verifiedCase(store, { id = "agent:verification", success = true } = {}) { const learning = createExperienceLearning({ store }); const verification = learning.verifyOutcome({ id, scopeId: "owner:local", taskId: `task:${id}`, outcomeKind: "task", success, evaluatorKind: "deterministic", criteria: [{ id: "complete", passed: success, evidenceRefs: [{ type: "receipt", id: `receipt:${id}`, version: "1" }] }], evidenceRefs: [{ type: "receipt", id: `receipt:${id}`, version: "1" }], environment: { family: "eclipse", runtime: "node20" }, independentGroup: `group:${id}`, verifiedBy: "local-owner" }); const experience = learning.createCase({ id: `case:${id}`, verificationId: verification.id, caseType: success ? "success" : "failure", taskSignature: "eclipse.agent.research", taskClass: "eclipse.agent.research", trajectorySummary: { outcome: success ? "verified_success" : "verified_failure" } }); return { verification, experience }; }
function publishEclipse(eclipse, overrides = {}) { return eclipse.publishMissionSnapshot({ scopeId: "owner:local", allowedScopeIds: ["owner:local"], missionId: "mission:atlas", sourceSequence: 1, status: "running", objective: "Produce a verified market brief", summary: "Research branches are resumable", missions: [ref("mission:atlas", "1", { visibility: "owner", capability: "eclipse.recall", trustZone: "trusted" })], branches: [ref("branch:research", "3", { visibility: "mission", subjectId: "mission:atlas", capability: "eclipse.recall" })], nodes: [ref("node:reader", "2", { visibility: "mission", subjectId: "mission:atlas", capability: "eclipse.recall" })], claims: [ref("claim:quarantine", "1", { visibility: "quarantined", capability: "eclipse.recall", trustZone: "untrusted" })], agents: [ref("agent:private", "4", { visibility: "agent_private", subjectId: "agent:reader", capability: "eclipse.recall", trustZone: "agent_private" })], evidence: [ref("evidence:source", "2", { visibility: "mission", subjectId: "mission:atlas", capability: "eclipse.recall" })], artifacts: [ref("artifact:report", "1", { visibility: "owner", capability: "eclipse.recall", trustZone: "trusted" })], reasoningTraceRefs: [{ id: "trace:hidden" }], privateAgentStateRefs: [{ id: "scratch:reader" }], ...overrides }); }
function confirmation(ops, action, target = {}) { return ops.createConfirmation({ scopeId: "owner:local", allowedScopeIds: ["owner:local"], actorId: "local-owner", authorityZone: "owner", action, ...target }); }
afterEach(() => { while (stores.length) stores.pop().close(); while (roots.length) fs.rmSync(roots.pop(), { recursive: true, force: true }); });

test("Waves 27-29 upgrade Wave 26 through a verified backup and keep every application table STRICT", async () => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "jarvis-memory-w2729-upgrade-")); roots.push(root); const old = await openCoreStore({ runtimeDir: root, allowUnsafeTestPath: true, keyProtector: protector(), targetVersion: 24 }); old.putEncryptedObject({ id: "before-wave27", objectType: "fixture", scopeId: "owner:local", payload: { survives: true } }); old.close(); const current = await openCoreStore({ runtimeDir: root, allowUnsafeTestPath: true, keyProtector: protector(), targetVersion: 27 }); stores.push(current); assert.deepEqual(current.getEncryptedObject("before-wave27").payload, { survives: true }); const audit = current.attachRepository(({ db }) => ({ version: Number(db.pragma("user_version", { simple: true })), backups: db.prepare("SELECT COUNT(*) AS count FROM backup_history").get().count, nonStrict: db.prepare("PRAGMA table_list").all().filter((row) => row.type === "table" && !String(row.name).startsWith("sqlite_") && row.strict !== 1).map((row) => row.name), migrations: db.prepare("SELECT version FROM schema_migrations ORDER BY version").all().map((row) => row.version) })); assert.equal(audit.version, 27); assert.equal(audit.backups, 1); assert.deepEqual(audit.nonStrict, []); assert.deepEqual(audit.migrations, Array.from({ length: 27 }, (_, index) => index + 1));
});

test("Wave 29 migration crash rolls back to Wave 28 and recovers without partial operations tables", async () => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "jarvis-memory-w29-fault-")); roots.push(root); const old = await openCoreStore({ runtimeDir: root, allowUnsafeTestPath: true, keyProtector: protector(), targetVersion: 26 }); old.close(); await assert.rejects(openCoreStore({ runtimeDir: root, allowUnsafeTestPath: true, keyProtector: protector(), targetVersion: 27, faultInjector(point) { if (point === "migration.27.before_commit") throw new Error("wave29 migration crash"); } }), /wave29 migration crash/); const Database = require("better-sqlite3"); const db = new Database(path.join(root, "memory-vnext.sqlite")); assert.equal(Number(db.pragma("user_version", { simple: true })), 26); assert.equal(db.prepare("SELECT COUNT(*) AS count FROM sqlite_schema WHERE type='table' AND name='backup_packages'").get().count, 0); db.close(); const recovered = await openCoreStore({ runtimeDir: root, allowUnsafeTestPath: true, keyProtector: protector(), targetVersion: 27 }); stores.push(recovered); assert.equal(recovered.health().schemaVersion, 27);
});

test("Wave 27 publishes resumable Eclipse state while filtering mission, quarantine, and agent-private recall", async () => {
  const store = await core(); const eclipse = createEclipseMemoryIntegration({ store }); const published = publishEclipse(eclipse); assert.equal(published.policyCount, 7); const owner = eclipse.recall({ missionId: "mission:atlas", requesterId: "local-owner", capabilities: ["eclipse.recall"], allowedScopeIds: ["owner:local"] }); assert.deepEqual(owner.refs.map((item) => item.id).sort(), ["artifact:report", "mission:atlas"]); const mission = eclipse.recall({ missionId: "mission:atlas", requesterId: "mission:atlas", capabilities: ["eclipse.recall"], allowedScopeIds: ["owner:local"] }); assert.deepEqual(mission.refs.map((item) => item.id).sort(), ["branch:research", "evidence:source", "node:reader"]); const agent = eclipse.recall({ missionId: "mission:atlas", requesterId: "agent:reader", capabilities: ["eclipse.recall"], allowedScopeIds: ["owner:local"] }); assert.deepEqual(agent.refs.map((item) => item.id), ["agent:private"]); const quarantine = eclipse.recall({ missionId: "mission:atlas", requesterId: "local-owner", capabilities: ["eclipse.recall", "eclipse.recall.quarantine"], includeQuarantined: true, allowedScopeIds: ["owner:local"] }); assert.equal(quarantine.refs.some((item) => item.id === "claim:quarantine"), true); assert.equal(owner.exclusions.length, 2); assert.equal(fs.readFileSync(store.paths.dbPath).includes(Buffer.from("Research branches are resumable")), false);
});

test("Wave 27 rejects raw reasoning and owner-wide untrusted state", async () => {
  const store = await core(); const eclipse = createEclipseMemoryIntegration({ store }); assert.throws(() => publishEclipse(eclipse, { missionId: "mission:reasoning", branches: [{ id: "branch:x", version: "1", reasoningTrace: "secret internal chain" }] }), (error) => error.code === "ECLIPSE_REASONING_TRACE_REJECTED"); assert.throws(() => publishEclipse(eclipse, { missionId: "mission:leak", sourceSequence: 1, claims: [ref("claim:bad", "1", { visibility: "owner", trustZone: "untrusted", capability: "eclipse.recall" })] }), (error) => error.code === "ECLIPSE_OWNER_WIDE_LEAK_REJECTED");
});

test("Wave 27 maps verified agent success and failure without promoting either as truth", async () => {
  const store = await core(); const eclipse = createEclipseMemoryIntegration({ store }); const manifest = publishEclipse(eclipse); const success = verifiedCase(store, { id: "verify:agent-success", success: true }); const failure = verifiedCase(store, { id: "verify:agent-failure", success: false }); const one = eclipse.recordAgentOutcome({ scopeId: "owner:local", manifestId: manifest.id, missionId: "mission:atlas", agentId: "agent:reader", verificationId: success.verification.id, experienceCaseId: success.experience.id }); const two = eclipse.recordAgentOutcome({ scopeId: "owner:local", manifestId: manifest.id, missionId: "mission:atlas", agentId: "agent:reader", verificationId: failure.verification.id, experienceCaseId: failure.experience.id }); assert.equal(one.promotable, false); assert.equal(two.result, "failure"); assert.throws(() => eclipse.readAgentExperience({ missionId: "mission:atlas", requesterId: "local-owner", capabilities: [], allowedScopeIds: ["owner:local"] }), (error) => error.code === "ECLIPSE_CAPABILITY_DENIED"); const rows = eclipse.readAgentExperience({ missionId: "mission:atlas", requesterId: "local-owner", capabilities: ["eclipse.recall.agent_outcome"], allowedScopeIds: ["owner:local"] }); assert.deepEqual(rows.map((item) => item.result), ["success", "failure"]); assert.ok(rows.every((item) => item.promotable === false));
});

test("Wave 28 creates signed encrypted packets under non-delegable selective-sync leases", async () => {
  const store = await core(); const mesh = createMeshMemorySync({ store }); const peer = mesh.registerPeer({ scopeId: "owner:local", identity: { node: "laptop-b", publicKeyFingerprint: "fixture" } }); const lease = mesh.issueLease({ scopeId: "owner:local", peerId: peer.id, sessionId: "session:one", capabilities: ["mesh.memory.share"], resources: ["artifact:*"] }); assert.equal(lease.mayDelegate, false); const sessionKey = crypto.randomBytes(32); const outbound = mesh.createOutbound({ scopeId: "owner:local", peerId: peer.id, sessionId: "session:one", leaseId: lease.id, sessionKey, nodeId: "node:a", packetType: "memory_packet", refType: "artifact", refId: "artifact:brief", refVersion: "3", payload: { summary: "Shared decision packet", sourceRefs: [{ id: "source:1", version: "2" }] } }); assert.notEqual(outbound.wire.ciphertext.includes("Shared decision packet"), true); const packets = mesh.listPackets({ scopeId: "owner:local", allowedScopeIds: ["owner:local"], peerId: peer.id, sessionId: "session:one", leaseId: lease.id, capability: "mesh.memory.share", resource: "artifact:brief" }); assert.equal(packets[0].payload.summary, "Shared decision packet"); assert.equal(fs.readFileSync(store.paths.dbPath).includes(Buffer.from("Shared decision packet")), false); sessionKey.fill(0);
});

test("Wave 28 accepts offline HLC delivery, marks late packets, deduplicates replay, and rejects clock skew", async () => {
  let senderMs = Date.parse("2026-07-26T12:00:00.000Z"); const receiverMs = senderMs + 2000; const sender = await core({ clock: () => new Date(senderMs) }); const receiver = await core({ clock: () => new Date(receiverMs) }); const a = createMeshMemorySync({ store: sender }); const b = createMeshMemorySync({ store: receiver });
  for (const mesh of [a, b]) { mesh.registerPeer({ id: "peer:shared", scopeId: "owner:local", identity: { node: "shared-remote" } }); mesh.issueLease({ id: "lease:shared", scopeId: "owner:local", peerId: "peer:shared", sessionId: "session:offline", expiresAt: new Date(receiverMs + 3600000).toISOString(), capabilities: ["mesh.memory.share"], resources: ["artifact:*"] }); }
  const key = crypto.randomBytes(32); const first = a.createOutbound({ id: "envelope:first", scopeId: "owner:local", peerId: "peer:shared", sessionId: "session:offline", leaseId: "lease:shared", sessionKey: key, nodeId: "node:sender", packetType: "memory_packet", refType: "artifact", refId: "artifact:first", refVersion: "1", payload: { summary: "created while offline" } }); senderMs += 1; const second = a.createOutbound({ id: "envelope:second", scopeId: "owner:local", peerId: "peer:shared", sessionId: "session:offline", leaseId: "lease:shared", sessionKey: key, nodeId: "node:sender", packetType: "memory_packet", refType: "artifact", refId: "artifact:second", refVersion: "1", payload: { summary: "newer offline packet" } }); const newest = b.ingest({ wire: second.wire, sessionKey: key, leaseId: "lease:shared", allowedScopeIds: ["owner:local"] }); assert.equal(newest.state, "current"); assert.equal(b.ingest({ wire: second.wire, sessionKey: key, leaseId: "lease:shared", allowedScopeIds: ["owner:local"] }).replayed, true); const late = b.ingest({ wire: first.wire, sessionKey: key, leaseId: "lease:shared", allowedScopeIds: ["owner:local"] }); assert.equal(late.state, "late"); assert.equal(late.advancedReplayPointer, false);
  senderMs = receiverMs + 600000; const future = a.createOutbound({ id: "envelope:future", scopeId: "owner:local", peerId: "peer:shared", sessionId: "session:offline", leaseId: "lease:shared", sessionKey: key, nodeId: "node:sender", packetType: "memory_packet", refType: "artifact", refId: "artifact:future", refVersion: "1", payload: { summary: "future packet" } }); assert.throws(() => b.ingest({ wire: future.wire, sessionKey: key, leaseId: "lease:shared", allowedScopeIds: ["owner:local"], maxClockSkewMs: 300000 }), (error) => error.code === "MESH_CLOCK_SKEW"); const tampered = { ...first.wire, ciphertext: `${first.wire.ciphertext.slice(0, -2)}AA` }; assert.throws(() => b.ingest({ wire: tampered, sessionKey: key, leaseId: "lease:shared", allowedScopeIds: ["owner:local"] }), (error) => error.code === "MESH_SIGNATURE_INVALID"); key.fill(0);
});

test("Wave 28 rejects databases, unauthorized resources, and canonical-memory CRDT use", async () => {
  const store = await core(); const mesh = createMeshMemorySync({ store }); const peer = mesh.registerPeer({ scopeId: "owner:local", identity: { node: "phone" } }); const lease = mesh.issueLease({ scopeId: "owner:local", peerId: peer.id, sessionId: "session:safe", capabilities: ["mesh.memory.share", "mesh.crdt.write"], resources: ["artifact:allowed", "layout:*"] }); const key = crypto.randomBytes(32); assert.throws(() => mesh.createOutbound({ scopeId: "owner:local", peerId: peer.id, sessionId: "session:safe", leaseId: lease.id, sessionKey: key, packetType: "memory_packet", refType: "artifact", refId: "artifact:allowed", refVersion: "1", payload: { databaseBytes: "sqlite bytes" } }), (error) => error.code === "MESH_FORBIDDEN_SYNC_BODY"); assert.throws(() => mesh.createOutbound({ scopeId: "owner:local", peerId: peer.id, sessionId: "session:safe", leaseId: lease.id, sessionKey: key, packetType: "memory_packet", refType: "artifact", refId: "artifact:denied", refVersion: "1", payload: { summary: "x" } }), (error) => error.code === "MESH_CAPABILITY_DENIED"); assert.throws(() => mesh.createOutbound({ scopeId: "owner:local", peerId: peer.id, sessionId: "session:safe", leaseId: lease.id, sessionKey: key, packetType: "crdt_update", refType: "layout", refId: "layout:memory", refVersion: "1", payload: { documentType: "canonical_memory", documentRef: "truth", version: 1, update: "x" } }), (error) => error.code === "MESH_CRDT_DOMAIN_DENIED"); key.fill(0);
});

test("Wave 28 enforces duplicate identity, revocation, expiry, and share removal", async () => {
  let nowMs = Date.parse("2026-07-26T12:00:00.000Z"); const store = await core({ clock: () => new Date(nowMs) }); const mesh = createMeshMemorySync({ store }); const peer = mesh.registerPeer({ scopeId: "owner:local", identity: { node: "tablet" } }); const lease = mesh.issueLease({ scopeId: "owner:local", peerId: peer.id, sessionId: "session:expiry", expiresAt: new Date(nowMs + 10000).toISOString(), capabilities: ["mesh.memory.share"], resources: ["artifact:*"] }); const key = crypto.randomBytes(32); const out = mesh.createOutbound({ id: "envelope:one", scopeId: "owner:local", peerId: peer.id, sessionId: "session:expiry", leaseId: lease.id, sessionKey: key, expiresAt: new Date(nowMs + 5000).toISOString(), packetType: "memory_packet", refType: "artifact", refId: "artifact:x", refVersion: "1", payload: { summary: "temporary" } }); assert.ok(out.wire.signature); const expiringLease = mesh.issueLease({ scopeId: "owner:local", peerId: peer.id, sessionId: "session:ttl", expiresAt: new Date(nowMs + 10000).toISOString(), capabilities: ["mesh.memory.share"], resources: ["artifact:*"] }); mesh.createOutbound({ id: "envelope:ttl", scopeId: "owner:local", peerId: peer.id, sessionId: "session:ttl", leaseId: expiringLease.id, sessionKey: key, expiresAt: new Date(nowMs + 5000).toISOString(), packetType: "memory_packet", refType: "artifact", refId: "artifact:ttl", refVersion: "1", payload: { summary: "expires naturally" } }); const revoke = mesh.revoke({ scopeId: "owner:local", peerId: peer.id, leaseId: lease.id, sessionId: "session:expiry", reasonCode: "OWNER_REVOKED" }); assert.ok(revoke.receiptMac); assert.throws(() => mesh.listPackets({ scopeId: "owner:local", allowedScopeIds: ["owner:local"], peerId: peer.id, sessionId: "session:expiry", leaseId: lease.id, capability: "mesh.memory.share", resource: "artifact:x" }), (error) => error.code === "MESH_LEASE_DENIED"); nowMs += 20000; assert.deepEqual(mesh.expireShares(), { packets: 1, leases: 1 }); key.fill(0);
});

test("Wave 29 requires one-time owner confirmations for operational controls", async () => {
  const store = await core(); const ops = createMemoryOperations({ store }); assert.throws(() => ops.createConfirmation({ scopeId: "owner:local", actorId: "local-system", authorityZone: "owner", action: "pause" }), (error) => error.code === "OWNER_AUTHORITY_REQUIRED"); const pause = confirmation(ops, "pause"); assert.deepEqual(ops.executeControl({ scopeId: "owner:local", actorId: "local-owner", authorityZone: "owner", action: "pause", confirmationId: pause.id }).mode, "paused"); assert.throws(() => ops.executeControl({ scopeId: "owner:local", actorId: "local-owner", authorityZone: "owner", action: "pause", confirmationId: pause.id }), (error) => error.code === "OPERATOR_CONFIRMATION_REQUIRED"); const resume = confirmation(ops, "resume"); assert.equal(ops.executeControl({ scopeId: "owner:local", actorId: "local-owner", authorityZone: "owner", action: "resume", confirmationId: resume.id }).mode, "running"); const integrity = confirmation(ops, "verify_integrity"); assert.equal(ops.executeControl({ scopeId: "owner:local", actorId: "local-owner", authorityZone: "owner", action: "verify_integrity", confirmationId: integrity.id }).integrityCheck, "ok");
});

test("Wave 29 creates encrypted online backups and passes an isolated restore drill", async () => {
  const store = await core(); store.putEncryptedObject({ id: "backup:fixture", objectType: "fixture", scopeId: "owner:local", payload: { privateText: "orchid restore fixture" } }); const ops = createMemoryOperations({ store }); const backupGate = confirmation(ops, "backup"); const backup = await ops.createBackup({ scopeId: "owner:local", actorId: "local-owner", authorityZone: "owner", confirmationId: backupGate.id, recoverySecret: "correct horse battery staple" }); assert.equal(backup.quickCheck, "ok"); assert.equal(backup.recoveryWrapped, true); const packageBytes = fs.readFileSync(backup.packagePath); assert.equal(packageBytes.includes(Buffer.from("orchid restore fixture")), false); const exportDir = fs.mkdtempSync(path.join(os.tmpdir(), "jarvis-offdevice-backup-")); roots.push(exportDir); const exportGate = confirmation(ops, "backup_export"); const exported = ops.exportBackup({ scopeId: "owner:local", actorId: "local-owner", authorityZone: "owner", confirmationId: exportGate.id, backupId: backup.id, targetDir: exportDir }); assert.equal(exported.packageSha256, backup.packageSha256); assert.equal(fs.existsSync(exported.targetPath), true); const restoreGate = confirmation(ops, "restore_verify"); const drill = await ops.verifyRestore({ scopeId: "owner:local", actorId: "local-owner", authorityZone: "owner", confirmationId: restoreGate.id, backupId: backup.id, recoverySecret: "correct horse battery staple", preferRecovery: true }); assert.equal(drill.status, "passed"); assert.equal(drill.result.recoveryPathUsed, true); assert.equal(drill.result.golden.encryptedSample, true); assert.equal(fs.existsSync(path.join(store.paths.rootDir, "restore-drills", `${drill.drillId}.sqlite`)), false);
});

test("Wave 29 rebuilds projections through bounded event snapshots and exposes every command-center surface", async () => {
  const store = await core(); const ops = createMemoryOperations({ store }); const gate = confirmation(ops, "projection_rebuild"); const rebuild = ops.rebuildProjection({ scopeId: "owner:local", actorId: "local-owner", authorityZone: "owner", confirmationId: gate.id, projector: "fixture-projector", version: "2", activate: true }); assert.equal(rebuild.status, "passed"); assert.equal(rebuild.activated, true); const soak = ops.runPerformanceSoak({ samples: 20, maxP95Ms: 1000 }); assert.equal(soak.status, "passed"); const model = ops.commandCenterModel(); for (const surface of ["overview", "conversationCortex", "truth", "context", "workers", "cache", "consistency", "consolidation", "forget", "privacy", "operations"]) assert.ok(model[surface]); assert.equal(model.confirmationRequired, true); assert.equal(model.consistency.projections[0].projector, "fixture-projector");
});

test("Waves 27-29 controlled faults leave no partial Eclipse, Mesh, or backup payloads", async () => {
  let crashPoint = null; const store = await core({ faultInjector(point) { if (point === crashPoint) throw new Error(`controlled ${point}`); } }); const eclipse = createEclipseMemoryIntegration({ store }); crashPoint = "eclipse.publish.before_commit"; assert.throws(() => publishEclipse(eclipse, { missionId: "mission:fault" }), /controlled/); crashPoint = null; const mesh = createMeshMemorySync({ store }); const peer = mesh.registerPeer({ scopeId: "owner:local", identity: { node: "fault-peer" } }); const lease = mesh.issueLease({ scopeId: "owner:local", peerId: peer.id, sessionId: "session:fault", capabilities: ["mesh.memory.share"], resources: ["artifact:*"] }); const key = crypto.randomBytes(32); crashPoint = "mesh.outbound.before_commit"; assert.throws(() => mesh.createOutbound({ scopeId: "owner:local", peerId: peer.id, sessionId: "session:fault", leaseId: lease.id, sessionKey: key, packetType: "memory_packet", refType: "artifact", refId: "artifact:fault", refVersion: "1", payload: { summary: "rollback" } }), /controlled/); crashPoint = null; const ops = createMemoryOperations({ store }); const gate = confirmation(ops, "backup"); crashPoint = "operations.backup.before_commit"; await assert.rejects(ops.createBackup({ scopeId: "owner:local", actorId: "local-owner", authorityZone: "owner", confirmationId: gate.id }), /controlled/); crashPoint = null; const state = store.attachRepository(({ db }) => ({ rooms: db.prepare("SELECT COUNT(*) AS count FROM room_manifests").get().count, eclipsePolicies: db.prepare("SELECT COUNT(*) AS count FROM eclipse_manifest_policies").get().count, envelopes: db.prepare("SELECT COUNT(*) AS count FROM mesh_sync_envelopes").get().count, packets: db.prepare("SELECT COUNT(*) AS count FROM mesh_shared_packets").get().count, backups: db.prepare("SELECT COUNT(*) AS count FROM backup_packages").get().count, backupPayloads: db.prepare("SELECT COUNT(*) AS count FROM encrypted_objects WHERE object_type='backup-package-manifest'").get().count })); assert.deepEqual(state, { rooms: 0, eclipsePolicies: 0, envelopes: 0, packets: 0, backups: 0, backupPayloads: 0 }); assert.equal(fs.readdirSync(path.join(store.paths.rootDir, "backup-packages")).some((name) => name.endsWith(".jmbak")), false); key.fill(0);
});
